version: '3'

networks:
  produto_net:
    driver: bridge

volumes:
  mongodb:
  movies:
  

services:
  mongo:
    image: mongo:4.4.3
    restart: always
    networks:
      - produto_net
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
  web:
    build: .
    depends_on:
      - mongo
    ports:
      - 5000:5000
    networks:
      - produto_net
    volumes:
      - .:/app
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - produto_net
    volumes:
      - mongodb:/data/db
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopwd@mongo:27017/

